### ISSUE TITLE
Assertion Error

### ISSUE THREAD

**Issue by noumanriazkhan** [octiapp/KerasPersonLab#6]
10993/16028 [===================>..........] - ETA: 59:31 - loss: 152848912.0000Traceback (most recent c
all last):
  File "train.py", line 77, in <module>
    epochs=config.NUM_EPOCHS, callbacks=callbacks)
  File "/root/anaconda3/envs/deep_source/lib/python3.6/site-packages/keras/engine/training.py", line 103
7, in fit
    validation_steps=validation_steps)
  File "/root/anaconda3/envs/deep_source/lib/python3.6/site-packages/keras/engine/training_arrays.py", l
ine 154, in fit_loop
    outs = f(ins)
  File "/root/anaconda3/envs/deep_source/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py
", line 2666, in __call__
    return self._call(inputs)
  File "/root/anaconda3/envs/deep_source/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 2636, in _call
    fetched = self._callable_fn(*array_vals)
  File "/root/anaconda3/envs/deep_source/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1382, in __call__
    run_metadata_ptr)
  File "/root/anaconda3/envs/deep_source/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 519, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.UnknownError: AssertionError:
Traceback (most recent call last):

  File "/root/anaconda3/envs/deep_source/lib/python3.6/site-packages/tensorflow/python/ops/script_ops.py", line 206, in __call__
    ret = func(*args)

  File "/root/networks/KerasPersonLab/tf_data_generator.py", line 71, in transform_data
    kp_maps, short_offsets, mid_offsets, long_offsets = get_ground_truth(instance_masks, kp)

  File "/root/networks/KerasPersonLab/data_prep.py", line 16, in get_ground_truth
    assert(instance_masks.shape[-1] == len(all_keypoints))

AssertionError

The error pretty much explain itself, not sure why shape is mis-matching.

**Comment by arf-akr** [comment]
42032/64115 [==================>...........] - ETA: 2:43:46 - loss: 6.3481Traceback (most recent call last):
  File "train.py", line 80, in <module>
    epochs=config.NUM_EPOCHS, callbacks=callbacks)
  File "/home/aakar/anaconda3/envs/myenv27/lib/python2.7/site-packages/keras/engine/training.py", line 1039, in fit
    validation_steps=validation_steps)
  File "/home/aakar/anaconda3/envs/myenv27/lib/python2.7/site-packages/keras/engine/training_arrays.py", line 154, in fit_loop
    outs = f(ins)
  File "/home/aakar/anaconda3/envs/myenv27/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py", line 2715, in __call__
    return self._call(inputs)
  File "/home/aakar/anaconda3/envs/myenv27/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py", line 2675, in _call
    fetched = self._callable_fn(*array_vals)
  File "/home/aakar/anaconda3/envs/myenv27/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1399, in __call__
    run_metadata_ptr)
  File "/home/aakar/anaconda3/envs/myenv27/lib/python2.7/site-packages/tensorflow/python/framework/errors_impl.py", line 526, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.UnknownError: exceptions.AssertionError: 
Traceback (most recent call last):

  File "/home/aakar/anaconda3/envs/myenv27/lib/python2.7/site-packages/tensorflow/python/ops/script_ops.py", line 206, in __call__
    ret = func(*args)

  File "/home/aakar/dlwork/KerasPersonLab/tf_data_generator.py", line 71, in transform_data
    kp_maps, short_offsets, mid_offsets, long_offsets = get_ground_truth(instance_masks, kp)

  File "/home/aakar/dlwork/KerasPersonLab/data_prep.py", line 16, in get_ground_truth
    assert(instance_masks.shape[-1] == len(all_keypoints))

AssertionError

I had the same error. Could you figure out a way to handle the error?

**Comment by jricheimer** [comment]
Hello @noumanriazkhan @aakar83,
Sorry for the delay in dealing with this. It has been fixed with a small fix. See [here](https://github.com/octiapp/KerasPersonLab/issues/8#issuecomment-483312427)

You will have to delete your hdf5 from before and re-run the `generate_hdf5` script.
